// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("14784c5c-7668-4a23-8251-97e345a28392"),
	startsWith("2b5f453d-3140-4e32-8740-6442dc5867b4"),
	endsWith("fa268f40-7f3e-4b3a-982e-08a6c52cd8dd"),
	between("9de539ec-3de0-464d-ab8c-9c15bc09a609"),
	greater("c43b504a-ac71-4c10-ac3d-86d97049a478"),
	greaterEqual("64b96456-7664-4675-9ad1-a546256eab4f"),
	equal("0a7323e0-8282-487f-944f-ac4ff326d40b"),
	notEqual("a281e260-12f0-406d-b744-29dd8aab01f7"),
	smaller("1fa5afb1-6cd1-4474-8749-6f9dc91176a1"),
	smallerEqual("d75e1cad-e9d0-4887-91d8-84c8035e52a0"),
	empty("fbe34619-1fa0-4333-879c-1bd454286505"),
	notEmpty("da55d1a7-d9fb-40dd-a83c-1cdfdd3777ee");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
