// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("840f3a4c-3cd2-40ad-802b-e26e31e61ec3"),
	startsWith("0ce76e4e-410e-416d-a1df-b67814f553fb"),
	endsWith("34ebe890-9a01-4560-b3be-7384ac8fa553"),
	between("22920745-e879-4159-94ec-33120e09081c"),
	greater("d5f19a37-53ba-4f7d-bf4e-89d14d7d4c91"),
	greaterEqual("dffbd816-1e23-43dc-ab8b-371ba44ddacd"),
	equal("4fb9d162-9bb3-4f75-ba67-6bd92b1b4fdd"),
	notEqual("b104e53c-48e1-421a-82da-662ad85212b5"),
	smaller("83292608-e1c8-47f8-952f-ed5ba2615f6f"),
	smallerEqual("40303afc-045a-4ca0-8a41-639cfe914672"),
	empty("1a725f7e-3c86-452e-bd31-4416da1c0d1d"),
	notEmpty("67897450-83af-420b-ad53-f55f2e89044b");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
