// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("9964e611-97e5-4fe0-8c55-1ce0b31216a7"),
	startsWith("e07cce02-e4bf-401e-898e-a5c9f18b6ba0"),
	endsWith("a405d052-3e93-402d-b1b8-14c144c05290"),
	between("015fae20-7e41-4ad3-b952-1de248099948"),
	greater("974f9e55-70e3-4005-88d9-bb51216914e8"),
	greaterEqual("93a665b4-c451-4bcb-9fc9-a5bd2180e3c0"),
	equal("72e3c854-4f4b-463f-84bf-175d56d9d7ee"),
	notEqual("138827e2-07f4-4672-9e81-8721dc1daccf"),
	smaller("bb547368-7062-4800-9287-eaa95f617fe4"),
	smallerEqual("fc6114e8-5db0-4426-9ef0-bee7a5557bf0"),
	empty("cec43665-a5ef-4845-a462-7bfea33689c2"),
	notEmpty("c892e590-3733-4df7-b7ee-1847ec19477c");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
