// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_TestContext_OnChangeSplitter(IContext context, myfirstmodule.proxies.TestContext _testContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestContext", _testContext == null ? null : _testContext.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_TestContext_OnChangeSplitter").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.TestContext dS_TestContext(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_TestContext").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.TestContext.initialize(context, result);
	}
	public static myfirstmodule.proxies.TestContext sUB_TestContext_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.SUB_TestContext_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.TestContext.initialize(context, result);
	}
}